.ORG 1000h; carga el programa en la posición 1000h






INICIO:

LXI D,1100;	carga un par de registros(DE) con un valor 

MVI C,00h;  carga el registro c con eun valor 0 en hexadecimal

JMP PARTE_DOS;

JMP bucle

bucle:

MVI A,7AH; 
STAX D; 	CARGAEL CONTENIDO DEL ACUMULADOR EN LA POSICION DE MEMORIA INDICADA POR D

INR C; 	INCREMENTA EN UNA UNIDAD EL REGISTRO C

INX D;	INCREMENTA UNA UNIDAD EN UN PAR DE REGISTROS(DE)

MOV A,C;	MUEVE C AL REGISTRO A

CPI 5H;	COMPARA EL VALOR DEL ACUMULADOR CON EL VALOR MOSTRADO

JNZ bucle;

RST 1;	ES UNA INTERRUPCIÓN QUE IMPIDE QUE SE MODIFIQUE EL ESTADO DE LOS REGISTROS
JMP FIN;





PARTE_DOS:

		LXI H, 1100H
		MVI C,5H

		JMP PROGRAMA

	PROGRAMA:

MVI B,00H
MVI D,00H
MVI E,00H

JMP BUCLE2

BUCLE2:

MVI M,7AH; 	MUEVE 7AH A LA POSICION DE MEMORIA INDICADA POR LOS REGISTROS HL
DCR C;	DECREMENTA UNA UNIDAD EL REGISTRO C(DE 5 A 4)
INX H;	INCREMENTA UN PAR DE REGISTROS (HL)
JNZ BUCLE2;	SALTO SI NO ES CERO,VA CON LA INSTRUCCIÓN DECREMENTAR
RST 1;	ES UNA INTERRUPCCION WUE IMPIDE QUE SE MODIFIQUE EL ESTADO DE LOS REGISTROS

HLT


FIN:

HLT

