.ORG 0H; PROGRAMA SUMA


EMPEZAR:

	JMP INICIO_4



INICIO:

				;SUMAR 2 NUMEROS
	MVI B,00H
	MVI A,00H
	MVI B,05H
	MVI A,03H
	ADD B; SUMAMOS B AL ACUMULADOR Y LO ALMACENAMOS EN A.





INICIO2:

			;SUMAR 3 NUMEROS CON POSICIONES DE MEMORIA


	MVI A,00H
	MVI B,00H; A Y B LOS PONEMOS A 00H

	MVI A,05H
	STA 0100H; CARGAMOS 05H EN LA POSICION 100H

	MVI A,01H
	STA 101H; CARGAMOS 01H EN LA POSICION 101H

	MVI A,02H
	STA 102H; CARGAMOS 02H EN LA POSICION 102H

	LDA 0100H
	MOV B,A; PONEMOS EN B EL VALOR DE LA POSICIÓN 100H

	MVI A,00H
	ADD B;    SUMAMOS B AL REGISTRO A.

	STA 099H;CARGAMOS EL RESULTADO SIEMPRE EN LA MISMA MEMORIA 

	LDA 101H
	MOV B,A; PONEMOS EN B EL VALOR DE LA POSICIÓN 101H
	LDA 099H; CARGAMOS EN A EL RESULTADO
	ADD B;    LE SUMAMOS AL RESULTADO EL REGISTRO B
	STA 099H; PONEMOS EL NUEVO RESULTADO EN LA POSICION DE RESULTADO

	LDA 102H
	MOV B,A; PONEMOS EN B EL VALOR DE LA POSICION 102H
	LDA 099H
	ADD B; SUMAMOS B AL ÚLTIMO RESULTADO OBTENIDO
	STA 099H; CARGAMOS EL RESULTADO FINAL EN LA POSICION RESERVADA.




INICIO_3:

			;MULTIPLICAR

MVI A,5H
MVI B,5H
MOV C,B
MVI A,00H
MVI H,00H
MVI L,00H

MULTIPLICA:

;MULTIPLICAR DOS NÚMEROS

ADI 01H	;SUMAMOS 01H AL REGISTRO A EN CADA VUELTA.
DAD B		;SUMAMOS B AL REGISTRO B Y C AL REGISTRO C, LOS ALMACENAMOS EN HL EN CADA VUELTA. 
CMP C		;COMPARAMOS EL REGISTRO A CON EL C
JC MULTIPLICA



INICIO_4:
			;DIVIDIR

MVI A,9H
MVI B,2H
MVI C,0H

DIVISION:

	SUB B
	INR C
	CMP B
	STA 100H ; RESTO EN LA POSICIÓN DE MEMORIA 100H
	JP DIVISION ; SI ES POSITIVO EL REGISTRO A QUE SIGA RESTANDO
	;JZ FIN; SI ES CERO LA DIVISION ES EXACTA
 
FIN:
	HLT	