.DEFINE 

	NUM1 9H
	NUM2 9H
	NUM3 2H


.ORG 0H

;GUARDAR EN EL REGISTRO D EL MAYOR DE LOS 3 VALORES

;SI A=REGISTRO 	Z=1
;A < REGISTRO 	C=1
;A > REGISTRO  	Z=0 Y C=0

;EL REGITRO H TENDRA EL MAYOR DE LOS TRES


CARGO_EN_REGISTRO:

	MVI A,NUM1
	MVI B,NUM2
	MVI C,NUM3

COMPARO_B:

	CMP B  		;COMPARAMOS A CON B
	JC COMPARO_C	;SI B > A SALTAMOS A LA SUBRUTINA "COMPARO_C" 
	JMP PASO_2		;SI A > B, O IGUAL SALTAMOS AL PASO B.

COMPARO_C:
	MOV A,B		;SI B > A, MOVEMOS EL VALOR DE B AL ACUMULADOR.



PASO_2:			
	CMP C			;SI A >= B, COMPARAMOS A CON C.
	JC MAYOR_C		;SI C < A , SALTAMOS A MAYOR_C.
	JMP MAYOR_A		;DE LO CONTRARIO(A > B Y C) Y SALTAMOS A MAYOR_A

MAYOR_C:
	MOV D,C		;SI C ES EL MAYOR LO MOVEMOS AL REGISTRO D
	JMP FIN

MAYOR_A:
	MOV D,A		;MOVEMOS EL VALOR DE A AL REGISTRO D.
	JMP FIN		

FIN:
	HLT

TECLADO:
	IN 00H; PARA INTRODUCIR EL VALOR EN UN PUERTO.
	CPI 0H
	JZ TECLADO;
	MOV C,A; PARA GUARDAR LA ULTIMA PULSACION	
	;PARA SACAR EL VALOR DE UN PUERTO PONER "OUT".



