.ORG 1000H


INICIO:

	MVI A,00h
	MVI B,00h
	MVI C,00h
	MVI D,00h
	MVI E,00h;	PONEMOS TODOS LOS REGISTROS A 00
	MVI H,00h
	MVI L,00h

	MVI A,20D; Para dividir valores decimales
	MVI B,4D;
	MVI C,0D;

	JMP DIVISION

DIVISION:

	CMP B; SI ES A < B ENTONCES FIN (SE ENCIENDE EL BIT DE ESTADO C)
	JC FIN
	SUB B; RESTAMOS AL ACUMULADOR EL VALOR DEL REGISTRO B.
	INR C; INCREMENTAMOS EL REGISTRO C EN UNA UNIDAD
	JMP DIVISION

FIN:
	STA 1103H
	MOV A,C
	STA 1102H
	HLT
